export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js'
};

export default function PublicLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
