name: Pro / CI-CD
on:
  push:
    branches:
      - master

env:
  node-version: '20.11.0'
  cache-name: yarn-cache
  app-name: paynah-web
  AWS_DEFAULT_REGION: ${{ secrets.aws_region }}
  AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key_id }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_access_key }}

jobs:
  build:
    name: Pro / Build and push
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Caching Docker
        id: docker-cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.docker
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Building docker image
        run: |
          aws ecr get-login-password --region ${{ secrets.aws_region }} | docker login --username AWS --password-stdin ${{ secrets.aws_ecr }}
          echo '${{ secrets.dev_env }}' > .env
          docker build -t ${{ secrets.aws_ecr }}/${{ env.app-name }}:${GITHUB_SHA::7} .
          docker push ${{ secrets.aws_ecr }}/${{ env.app-name }}:${GITHUB_SHA::7}

  deploy:
    runs-on: ubuntu-22.04
    name: Pro / Deploy
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Install kubectl
        run: |
          curl -o kubectl https://dl.k8s.io/release/v1.28.4/bin/linux/amd64/kubectl
          chmod +x ./kubectl
          mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$PATH:$HOME/bin
          echo 'export PATH=$PATH:$HOME/bin' >> ~/.bashrc
          mkdir -p ~/.kube
      - name: Install Helm
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh
          helm plugin install https://github.com/hypnoglow/helm-s3.git
      - name: Get kubeconfig
        run: |
          aws eks --region ${{ secrets.aws_region }} update-kubeconfig --name ${{ secrets.aws_eks_cluster }}
      - name: Add helm repo
        run: |
          helm repo add ${{ secrets.aws_eks_cluster }} ${{ secrets.helm_repo }}
      - name: Deploy to k8s
        run: |
          helm upgrade -i ${{ env.app-name }} -f .github/manifest/values.yaml \
            -n production --create-namespace \
            --set image.tag=${GITHUB_SHA::7} \
            paynah/app-generic
